// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikgjtecxqwsibcccfjfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrZ2p0ZWN4cXdzaWJjY2NmamZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMTUwOTAsImV4cCI6MjA2NDc5MTA5MH0.bhLMln7b5sPZk0X2Oatvn1fPcagmrfimE8n-ycckqJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);